import type { Favorite } from "@/types/favorites";

export const FAVORITES = [
  {
    category: "People",
    description: "Portfolio of a award winning songwriter",
    slug: "alan-menken",
    title: "Alan Menken",
    url: "https://alanmenken.com",
  },
  {
    category: "Development",
    description: "AI company I trust",
    slug: "anthropic",
    title: "Anthropic",
    url: "https://anthropic.com",
  },
  {
    category: "Products",
    description: "A minimal and beautiful clock screensaver for your mac.",
    slug: "bauhaus-clock",
    title: "Bauhaus Clock",
    url: "https://bauhausclock.com",
  },
  {
    category: "Design",
    description: "Top notch product & website design",
    slug: "clay",
    title: "Clay",
    url: "https://clay.earth",
  },
  {
    category: "Products",
    description: "All the things I wish to own someday",
    slug: "curated-supply",
    title: "Curated Supply",
    url: "https://curated.supply",
  },
  {
    category: "People",
    description: "Big fan of Darius' illustrations",
    slug: "darius-dan",
    title: "Darius Dan",
    url: "https://dariusdan.com",
  },
  {
    category: "Fonts",
    description: "Beautiful pixel mono font",
    slug: "departure-mono",
    title: "Departure Mono",
    url: "https://departuremono.com",
  },
  {
    category: "People",
    description: "The OG builder (and our investor)",
    slug: "dharmesh-shah",
    title: "Dharmesh Shah",
    url: "https://peerlist.io",
  },
  {
    category: "People",
    description: "My source of inspiration",
    slug: "dieter-rams",
    title: "Dieter Rams",
    url: "https://rams-foundation.org",
  },
  {
    category: "Design",
    description: "I live here. This is my second address.",
    slug: "figma",
    title: "Figma",
    url: "https://figma.com",
  },
  {
    category: "Products",
    description: "This app make avgeek within me happy",
    slug: "flighty",
    title: "Flighty",
    url: "https://flighty.com",
  },
  {
    category: "Development",
    description: "Lightweight Intercom alternative",
    slug: "foxchat",
    title: "Foxchat",
    url: "https://foxchat.dev",
  },
  {
    category: "People",
    description: "Designer at Linear",
    slug: "gavin-nelson",
    title: "Gavin Nelson",
    url: "https://nelson.co",
  },
  {
    category: "Fonts",
    description: "Product font I blindly use",
    slug: "geist-geist-mono",
    title: "Geist & Geist Mono",
    url: "https://vercel.com",
  },
  {
    category: "Products",
    description: "My companion in all sales calls",
    slug: "granola",
    title: "Granola",
    url: "https://granola.ai",
  },
  {
    category: "People",
    description: "Brilliant design leader",
    slug: "hardik-pandya",
    title: "Hardik Pandya",
    url: "https://hvpandya.com",
  },
  {
    category: "Icons",
    description: "Using these icons in all of my projects",
    slug: "hugeicons",
    title: "Hugeicons",
    url: "https://hugeicons.com",
  },
  {
    category: "Products",
    description: "Only generational wealth I will pass on",
    slug: "leica-m6",
    title: "Leica M6",
    url: "https://leica-camera.com",
  },
  {
    category: "Books",
    description: "For a bookworm in you",
    slug: "literal",
    title: "Literal",
    url: "https://literal.club",
  },
  {
    category: "Design",
    description: "So simple landing page",
    slug: "lovi",
    title: "Lovi",
    url: "https://lovi.care",
  },
  {
    category: "Design",
    description: "Minimal websites directory.",
    slug: "minimum",
    title: "Minimum",
    url: "https://mnmm.xyz",
  },
  {
    category: "People",
    description: "Click only if you've 2 hours to spare.",
    slug: "neal-agarwal",
    title: "Neal Agarwal",
    url: "https://neal.fun",
  },
  {
    category: "Design",
    description: "Design inspiration for og-images",
    slug: "ogimage-gallery",
    title: "ogimage Gallery",
    url: "https://ogimage.gallery",
  },
  {
    category: "Media",
    description: "A humble little film, maybe, but an enriching one.",
    slug: "perfect-days",
    title: "Perfect Days",
    url: "https://mubi.com",
  },
  {
    category: "Analytics",
    description: "Analytics with beauty and brain",
    slug: "seline",
    title: "Seline",
    url: "https://seline.com",
  },
  {
    category: "Media",
    description:
      "You guys wanna go and see a dead body? A cult classic that never gets old.",
    slug: "stand-by-me",
    title: "Stand By Me",
    url: "https://netflix.com",
  },
  {
    category: "Development",
    description: "Blog websites can be thoughtful",
    slug: "stripe-dev",
    title: "Stripe Dev",
    url: "https://stripe.dev",
  },
  {
    category: "Books",
    description: "Books I wish to own",
    slug: "stripe-press",
    title: "Stripe Press",
    url: "https://press.stripe.com",
  },
  {
    category: "Products",
    description: "Beautiful note taking and todo app",
    slug: "superlist",
    title: "Superlist",
    url: "https://superlist.com",
  },
  {
    category: "Media",
    description: "Stunning cinematography, and gentle pacing",
    slug: "the-dig",
    title: "The Dig",
    url: "https://netflix.com",
  },
  {
    category: "Icons",
    description: "Love their everyday 3d icons",
    slug: "thiings-co",
    title: "Thiings.co",
    url: "https://thiings.co",
  },
] as const satisfies readonly Favorite[];

export const FAVORITE_CATEGORIES = [
  "All",
  "Design",
  "Development",
  "People",
  "Products",
  "Media",
  "Books",
  "Fonts",
  "Icons",
  "Analytics",
] as const;
