export const ROUTES = {
  BLOCKS: "/blocks",
  BLOG: "/blog",
  COMPONENTS: "/components",
  CONTACT: "/contact",
  CRAFTS: "/crafts",
  EXPERIENCES: "/experiences",
  FAVORITES: "/favorites",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  PROJECTS: "/projects",
  RESUME: "/resume.pdf",
  SPONSORS: "/sponsors",
  STACK: "/stack",
  STATS: "/stats",
  VCARD: "/vcard",
} as const;
