export const ROUTES = {
  ABOUT: "/about",
  BLOCKS: "/blocks",
  BLOG: "/blog",
  COLOPHON: "/colophon",
  COMPONENTS: "/components",
  CONTACT: "/contact",
  CRAFTS: "/crafts",
  EXPERIENCES: "/experiences",
  FAVORITES: "/favorites",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MDX: "/llms.mdx",
  PROJECTS: "/projects",
  RESUME: "/resume.pdf",
  SPONSORS: "/sponsors",
  STATS: "/stats",
  TESTIMONIALS: "/testimonials",
  USES: "/uses",
  VCARD: "/vcard",
  WRITING: "/writing",
} as const;
