import { Icons } from "@/components/icons";
import type { TechStackItem } from "@/types/tech-stack";

export const TECH_STACK: TechStackItem[] = [
  {
    categories: ["Languages"],
    href: "https://www.typescriptlang.org",
    icon: <Icons.ts />,
    key: "typescript",
    title: "TypeScript",
  },
  {
    categories: ["Languages"],
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    icon: <Icons.js />,
    key: "javascript",
    title: "JavaScript",
  },
  {
    categories: ["Languages"],
    href: "https://www.python.org",
    icon: <Icons.python />,
    key: "python",
    title: "Python",
  },
  {
    categories: ["Design"],
    href: "https://www.figma.com",
    icon: <Icons.figma />,
    key: "figma",
    title: "Figma",
  },
  {
    categories: ["Design"],
    href: "https://www.paper.design",
    icon: <Icons.paper />,
    key: "paper",
    title: "Paper",
  },
  {
    categories: ["Design"],
    href: "https://www.pencil.dev",
    icon: <Icons.pencil />,
    key: "pencil",
    title: "Pencil",
  },
  {
    categories: ["Frontend"],
    href: "https://react.dev",
    icon: <Icons.react />,
    key: "react",
    title: "React",
  },
  {
    categories: ["Frontend"],
    href: "https://nextjs.org",
    icon: <Icons.nextjs />,
    key: "nextjs",
    title: "Next.js",
  },
  {
    categories: ["Frontend"],
    href: "https://tanstack.com",
    icon: <Icons.tanstack />,
    key: "tanstack",
    title: "TanStack",
  },
  {
    categories: ["Frontend"],
    href: "https://tailwindcss.com",
    icon: <Icons.tailwindcss />,
    key: "tailwindcss",
    title: "Tailwind CSS",
  },
  {
    categories: ["Frontend"],
    href: "https://ui.shadcn.com",
    icon: <Icons.shadcn />,
    key: "shadcn-ui",
    title: "shadcn/ui",
  },
  {
    categories: ["Frontend"],
    href: "https://www.radix-ui.com",
    icon: <Icons.radixui />,
    key: "radixui",
    title: "Radix UI",
  },
  {
    categories: ["Frontend"],
    href: "https://base-ui.com",
    icon: <Icons.baseui />,
    key: "base-ui",
    title: "Base UI",
  },
  {
    categories: ["Frontend"],
    href: "https://motion.dev",
    icon: <Icons.motion />,
    key: "motion",
    title: "Motion",
  },
  {
    categories: ["Frontend"],
    href: "https://fumadocs.dev",
    icon: <Icons.fumadocs />,
    key: "fumadocs",
    title: "Fumadocs",
  },
  {
    categories: ["Frontend"],
    href: "https://zod.dev",
    icon: <Icons.zod />,
    key: "zod",
    title: "Zod",
  },
  {
    categories: ["Frontend"],
    href: "https://redux.js.org",
    icon: <Icons.redux />,
    key: "redux",
    title: "Redux",
  },
  {
    categories: ["Frontend"],
    href: "https://zustand-demo.pmnd.rs/",
    icon: <Icons.zustand />,
    key: "zustand",
    title: "Zustand",
  },
  {
    categories: ["Backend & DB"],
    href: "https://better-auth.com",
    icon: <Icons.betterauth />,
    key: "better-auth",
    title: "Better Auth",
  },
  {
    categories: ["Backend & DB"],
    href: "https://clerk.com",
    icon: <Icons.clerk />,
    key: "clerk",
    title: "Clerk",
  },
  {
    categories: ["Backend & DB"],
    href: "https://firebase.google.com",
    icon: <Icons.firebase />,
    key: "firebase",
    title: "Firebase",
  },
  {
    categories: ["Backend & DB"],
    href: "https://supabase.com",
    icon: <Icons.supabase />,
    key: "supabase",
    title: "Supabase",
  },
  {
    categories: ["Backend & DB"],
    href: "https://convex.dev",
    icon: <Icons.convex />,
    key: "convex",
    title: "Convex",
  },
  {
    categories: ["Backend & DB"],
    href: "https://nodejs.org",
    icon: <Icons.nodejs />,
    key: "nodejs",
    title: "Node.js",
  },
  {
    categories: ["Backend & DB"],
    href: "https://bun.sh",
    icon: <Icons.bun />,
    key: "bun",
    title: "Bun",
  },
  {
    categories: ["Backend & DB"],
    href: "https://www.prisma.io",
    icon: <Icons.prisma />,
    key: "prisma",
    title: "Prisma",
  },
  {
    categories: ["Backend & DB"],
    href: "https://orm.drizzle.team",
    icon: <Icons.drizzle />,
    key: "drizzle",
    title: "Drizzle",
  },
  {
    categories: ["Backend & DB"],
    href: "https://www.postgresql.org",
    icon: <Icons.postgresql />,
    key: "postgresql",
    title: "PostgreSQL",
  },
  {
    categories: ["Backend & DB"],
    href: "https://www.mongodb.com",
    icon: <Icons.mongodb />,
    key: "mongodb",
    title: "MongoDB",
  },
  {
    categories: ["Backend & DB"],
    href: "https://redis.io",
    icon: <Icons.redis />,
    key: "redis",
    title: "Redis",
  },
  {
    categories: ["Dev Tools"],
    href: "https://better-t-stack.dev",
    icon: <Icons.bettertstack />,
    key: "bettertstack",
    title: "Better-T-Stack",
  },
  {
    categories: ["Dev Tools"],
    href: "https://react.doctor",
    icon: <Icons.reactdoctor />,
    key: "reactdoctor",
    title: "React Doctor",
  },
  {
    categories: ["Dev Tools"],
    href: "https://react-scan.com",
    icon: <Icons.reactscan />,
    key: "reactscan",
    title: "React Scan",
  },
  {
    categories: ["Dev Tools"],
    href: "https://git-scm.com",
    icon: <Icons.git />,
    key: "git",
    title: "Git",
  },
  {
    categories: ["Dev Tools"],
    href: "https://www.docker.com",
    icon: <Icons.docker />,
    key: "docker",
    title: "Docker",
  },
  {
    categories: ["AI"],
    href: "https://cursor.com",
    icon: <Icons.cursor />,
    key: "cursor",
    title: "Cursor",
  },
  {
    categories: ["AI"],
    href: "https://claude.com/product/claude-code",
    icon: <Icons.claude />,
    key: "claude",
    title: "Claude Code",
  },
  {
    categories: ["AI"],
    href: "https://pi.dev",
    icon: <Icons.pi />,
    key: "pi",
    title: "Pi",
  },
  {
    categories: ["AI"],
    href: "https://opencode.ai",
    icon: <Icons.opencode />,
    key: "opencode",
    title: "OpenCode",
  },
  {
    categories: ["AI"],
    href: "https://chatgpt.com/codex/",
    icon: <Icons.codex />,
    key: "codex",
    title: "Codex",
  },
  {
    categories: ["AI"],
    href: "https://antigravity.google",
    icon: <Icons.antigravity />,
    key: "Antigravity",
    title: "Antigravity",
  },
  {
    categories: ["Native Apps"],
    href: "https://reactnative.dev",
    icon: <Icons.reactnative />,
    key: "react-native",
    title: "React Native",
  },
  {
    categories: ["Native Apps"],
    href: "https://expo.dev",
    icon: <Icons.expo />,
    key: "expo",
    title: "Expo",
  },
  {
    categories: ["Native Apps"],
    href: "https://capacitorjs.com",
    icon: <Icons.capacitor />,
    key: "capacitor",
    title: "Capacitor",
  },
  {
    categories: ["Native Apps"],
    href: "https://www.electronjs.org",
    icon: <Icons.electron />,
    key: "electron",
    title: "Electron",
  },
  {
    categories: ["Native Apps"],
    href: "https://tauri.app",
    icon: <Icons.tauri />,
    key: "tauri",
    title: "Tauri",
  },
];
