import { ROUTES } from "@/constants/routes";
import registryJson from "@/registry.json";

/** Registry surfaces: single components vs. composed blocks. */
export type RegistryKind = "block" | "component";

export interface RegistryEntry {
  kind: RegistryKind;
  slug: string;
  title: string;
  description: string;
  category: string;
  dependencies: string[];
}

export interface RegistryKindConfig {
  kind: RegistryKind;
  /** Index route for the kind, e.g. `/components`. */
  route: string;
  /** Breadcrumb / metadata label. */
  label: string;
  /** Lowercase heading used on the index page. */
  heading: string;
  description: string;
  /** Metadata category for detail pages. */
  category: string;
  /** Copy shown when the kind has no published entries. */
  emptyState: string;
}

export const REGISTRY_KINDS: Record<RegistryKind, RegistryKindConfig> = {
  block: {
    category: "UI Block",
    description: "Open-source, composed UI blocks ready to drop into a page.",
    emptyState: "No blocks published yet.",
    heading: "blocks.",
    kind: "block",
    label: "Blocks",
    route: ROUTES.BLOCKS,
  },
  component: {
    category: "UI Component",
    description: "Open-source UI components and registry.",
    emptyState: "No components published yet.",
    heading: "components.",
    kind: "component",
    label: "Components",
    route: ROUTES.COMPONENTS,
  },
};

const KIND_BY_TYPE: Record<string, RegistryKind> = {
  "registry:block": "block",
  "registry:component": "component",
};

/**
 * `registry.json` is generated by `pnpm registry:build` from
 * `registry/index.ts`, so the site and the published registry never drift.
 */
const REGISTRY_ENTRIES: readonly RegistryEntry[] = registryJson.items.flatMap(
  (item) => {
    const kind = KIND_BY_TYPE[item.type];

    if (!kind) {
      return [];
    }

    return [
      {
        category: item.categories?.[0] ?? kind,
        dependencies: item.dependencies ?? [],
        description: item.description,
        kind,
        slug: item.name,
        title: item.title,
      },
    ];
  }
);

export const getRegistryEntries = (kind: RegistryKind): RegistryEntry[] =>
  REGISTRY_ENTRIES.filter((entry) => entry.kind === kind);

export const getRegistryEntryBySlug = (
  kind: RegistryKind,
  slug: string
): RegistryEntry | undefined =>
  REGISTRY_ENTRIES.find((entry) => entry.kind === kind && entry.slug === slug);

export const getRegistryEntrySlugs = (kind: RegistryKind): string[] =>
  getRegistryEntries(kind).map((entry) => entry.slug);

export const registryEntryHref = (entry: RegistryEntry): string =>
  `${REGISTRY_KINDS[entry.kind].route}/${entry.slug}`;

export const registryInstallCommand = (slug: string): string =>
  `npx shadcn@latest add "https://aniketpawar.com/r/${slug}.json"`;

export const registryPromptText = (slug: string): string =>
  `Add the @aniketui/${slug} component to my project.`;
