export const techLinks = {
  HTML5: "https://html.spec.whatwg.org/multipage/",
  CSS3: "https://www.w3.org/TR/css3-roadmap/",
  SASS: "https://sass-lang.com/",
  "Material UI": "https://material-ui.com/",
  JavaScript: "https://www.javascript.com/",
  React: "https://reactjs.org/",
  "Redux Saga": "https://redux-saga.js.org/",
  TypeScript: "https://www.typescriptlang.org/",
  "Node.js": "https://nodejs.org/",
  "Express.js": "https://expressjs.com/",
  MongoDB: "https://www.mongodb.com/",
  Mongoose: "https://mongoosejs.com/",
  Bootstrap: "https://getbootstrap.com/",
  PHP: "https://www.php.net/",
  MySQL: "https://www.mysql.com/",
  "Tailwind CSS": "https://tailwindcss.com/",
  "React Query": "https://react-query-v3.tanstack.com/",
  "React Hook Form": "https://react-hook-form.com/",
  "React Highcharts": "http://kirjs.github.io/react-highcharts/",
  "Next.js": "https://nextjs.org/",
  "Strapi CMS": "https://strapi.io/",
  Recoil: "https://recoiljs.org/",
  Firebase: "https://firebase.google.com/",
  AWS: "https://aws.amazon.com/",
  GCP: "https://cloud.google.com/",
};
